### ISSUE TITLE
Oxygen PI conversion can not handle nested comment

### ISSUE THREAD

**Issue by nkutsche** [oxygenxml/dita-classic-pdf-review#3]
At least in my Oxygen (20.1) I'm able to create nested comments, like this (as pseudo code):

```
[comment_1]comment with with [comment_2]includeing[/comment_2] comment[/comment_1]
```

My Oxygen creates this in the code:

```
<?oxy_comment_start` author="Nico" timestamp="20190704T112447+0200" comment="wrapper comment"?>
comment with 
<?oxy_comment_start author="Nico" timestamp="20190704T112459+0200" comment="including comment"?>
including
<?oxy_comment_end?>
 comment
<?oxy_comment_end?>
```

If I run the document with `review-pis-to-elements.xsl` I get this:

```
<oxy:oxy-range-start id="sc_1" hr_id="1"/>
<oxy:oxy-comment href="#sc_1" hr_id="1">
    [...]
</oxy:oxy-comment>
<oxy:oxy-comment-hl>comment with </oxy:oxy-comment-hl>
<oxy:oxy-range-start id="sc_2" hr_id="2"/>
<oxy:oxy-comment href="#sc_2" hr_id="2">
    [...]
</oxy:oxy-comment>
<oxy:oxy-comment-hl>including</oxy:oxy-comment-hl>
<oxy:oxy-range-end hr_id="2"/>
<oxy:oxy-comment-hl> comment</oxy:oxy-comment-hl>
<oxy:oxy-range-end hr_id="2"/>
```

You see, I get two `oxy-range-end` with `hr_id="2"`. On my perspective the last one should have `hr_id="1"`.

There is also a discussion in this [Oxygen forum topic](https://www.oxygenxml.com/forum/topic16772.html).

**Comment by raducoravu** [comment]
@nkutsche you are right, I will start to look into this. In a way although I did not write the XSLT I blame myself for adding the @mid attribute on the processing instructions only in very particular cases. As my original interpretation of these processing instructions was in Java I could store the start and end processing instructions in a Java Stack and find quite easily the pairs but this in XSLT it's harder to do.

**Comment by nkutsche** [comment]
@raducoravu : there is no true developer who has never been sorry for what he has done in the past. :-)

I think it is even not so hard in XSLT as it seems to be in the first glance. This is my current function to get from a start PI the corresponding end PI.

```
<xsl:function name="d2t:getEndPI" as="processing-instruction()?">
    <xsl:param name="start" as="processing-instruction()"/>
    <xsl:variable name="startName" select="name($start)"/>
    <xsl:variable name="endName" select="replace($startName, '_start$', '_end')"/>
    <xsl:variable name="followingPIs" select="$start/following::processing-instruction()
        [name() = ($endName, $startName)]"/>
    <xsl:variable name="followingEndPIs" select="
        $followingPIs[name() = $endName][
        every $endPi in . satisfies
        d2t:doTheyMatch($start, $endPi, $followingPIs[. &lt;&lt; $endPi])
        ]
        "/>
    <xsl:sequence select="$followingEndPIs[1]"/>
</xsl:function>

<xsl:function name="d2t:doTheyMatch" as="xs:boolean">
    <xsl:param name="piStart" as="processing-instruction()"/>
    <xsl:param name="piEnd" as="processing-instruction()"/>
    <xsl:param name="piBetween" as="processing-instruction()*"/>
    <xsl:sequence select="count($piBetween[name() = name($piStart)]) = count($piBetween[name() = name($piEnd)])"/>
</xsl:function>
```

It does not support the PIs with `@mid`, but this is not a big deal.

**Comment by raducoravu** [comment]
@nkutsche I committed a possible fix on the repository using your suggestions:
https://github.com/oxygenxml/dita-classic-pdf-review/commit/635f06d06f11fd24e9ecb50409c1c8665e49ebd5#diff-889545fa292a353b2664b5855a158450
but will probably need to create test case with more complicated situation. My fix should take @mid's into account.
