### ISSUE TITLE
Changes not shown for number-only text

### ISSUE THREAD

**Issue by nakohdo** [oxygenxml/dita-classic-pdf-review#6]
We've stumbled across a strange bug: If an entry consists only of numbers, the changes are not shown. As soon as you add any other character, for example a space, it works as expected. Could this be some implicit type casting gone wrong?

### Code sample

`<p>20<?oxy_delete author="nlvi" timestamp="20200727T093438+0200" content="16"?><?oxy_insert_start author="nlvi" timestamp="20200727T093438+0200"?>20<?oxy_insert_end?>0912</p>`

**Comment by raducoravu** [comment]
I cannot reproduce the problem with the current plugin contents, the PDF I obtained from your sample DITA content looks like this:

<img width="120" alt="Screen Shot 2020-09-02 at 1 57 25 PM" src="https://user-images.githubusercontent.com/1005979/91973062-44607880-ed24-11ea-99cb-f52a08d004c9.png">

**Comment by nakohdo** [comment]
Thanks for testing, Radu. I will check, whether our code is not up to date.

**Comment by nakohdo** [comment]
Cannot find any relevant differences in the plugin code. So might have to do something with our customized PDF plugin. Therefore closing this issue.
